Only apply Heptagon -memalloc optimization
-O applies
    -memalloc
    -itfusion
    -deadcode
    -tomato

But -tomato causes a compilation failure:

  ---------
  Internal compiler error
  Passe : Static evaluation failed of the pervasive operator =
  ----------
  Fatal error: exception Misc.Assert_false